- .circleci/config.yml
- escrow/.cargo/config
- escrow/Cargo.lock
- escrow/Cargo.toml
- escrow/examples/schema.rs
- escrow/schema/handle_msg.json
- escrow/schema/init_msg.json
- escrow/schema/query_msg.json
- escrow/schema/state.json
- escrow/src/contract.rs
Add script to auto-generate json schema for messages to the escrow contract.
This builds on work in https://github.com/confio/cosmwasm/pull/69 (cosmwasm v0.5.1) and these requirements https://github.com/confio/cosmwasm/issues/51
> Schema autogen

- escrow/src/contract.rs
- escrow/tests/integration.rs
See https://doc.rust-lang.org/std/vec/struct.Vec.html#method.first
> Use Vec.first() to access first result

- escrow/.gitignore
- escrow/tests/integration.rs
Closes #15 
Errors making minor config changes directly on master. Lesson learned
> Fix wasm location in integration test

- escrow/Cargo.lock
- escrow/Cargo.toml
- escrow/src/contract.rs
- escrow/tests/integration.rs
Demos how we can simplify code.
Look for other complex areas... CosmWasm 0.6.3 (will) add a number of helpers as error shorthand. Any other boilerplate to remove?
> Use cw storage in escrow contract

- .gitignore
- escrow/Cargo.lock
- escrow/Cargo.toml
- escrow/src/contract.rs
Following up on #25 this cleans up the escrow contract more using new cosmwasm helpers.
This should be quite clean to read now, without unnecessary boilerplate
> Use helpers in escrow

- erc20/src/contract/mod.rs
- erc20/src/contract/tests.rs
> Avoid misleading term "decimal" in parse_u128

- .circleci/config.yml
> Run tests explicitly

- .circleci/config.yml
and adapt cache keys to a per-job cache
> Upgrade Rust version to 1.40

- .circleci/config.yml
- erc20/src/contract.rs
- escrow/src/contract.rs
- nameservice/src/coin_helpers.rs
- nameservice/src/contract.rs
Closes #66
This can be merged into master/0.7. Rust version 1.41.1 is what we use in confio/cosmwasm-opt:0.7.3
> Add linting to CI

- nameservice/Cargo.lock
- nameservice/Cargo.toml
- nameservice/examples/schema.rs
- nameservice/schema/init_msg.json
- nameservice/schema/resolve_record_response.json
- nameservice/src/coin_helpers.rs
- nameservice/src/contract.rs
- nameservice/src/lib.rs
- nameservice/src/msg.rs
- nameservice/src/state.rs
- nameservice/src/tests.rs
- nameservice/tests/integration.rs
> Update nameservice contract to 0.8

- escrow/Cargo.lock
- escrow/Cargo.toml
- escrow/examples/schema.rs
- escrow/schema/handle_msg.json
- escrow/schema/init_msg.json
- escrow/schema/state.json
- escrow/src/contract.rs
- escrow/src/lib.rs
- escrow/src/msg.rs
- escrow/src/state.rs
- escrow/tests/integration.rs
Based on #67
Part of #65
---------
There are a few TODOs left.
~Biggest question is how to update mock balances in integration tests. I found a way for unit tests but this cannot be adapted directly.~
> Update escrow contract to 0.8

- escrow/schema/query_msg.json
- escrow/src/contract.rs
- escrow/src/msg.rs
- escrow/tests/integration.rs
> Add query to escrow

- erc20/Cargo.lock
- erc20/Cargo.toml
- escrow/Cargo.lock
- escrow/Cargo.toml
- mask/Cargo.lock
- mask/Cargo.toml
- mask/schema/handle_msg.json
- nameservice/Cargo.lock
- nameservice/Cargo.toml
> Upgrade to CosmWasm to 0.9.1

- voting/Cargo.lock
- voting/Cargo.toml
- voting/src/contract.rs
- voting/src/tests.rs
- voting/tests/integration.rs
Bug slipped in with a refactor, the poll status is rejected even if passed.
> Fix the status on ending polls

- erc20/Cargo.lock
- erc20/Cargo.toml
- erc20/src/contract.rs
- erc20/src/error.rs
- erc20/src/lib.rs
- erc20/src/tests.rs
- erc20/tests/integration.rs
Related to https://github.com/CosmWasm/cosmwasm-examples/issues/94
> erc20: Migrate cosmwasm to 0.11.0

- escrow/Cargo.lock
- escrow/Cargo.toml
- escrow/src/contract.rs
- escrow/src/error.rs
- escrow/src/lib.rs
- escrow/src/state.rs
- escrow/tests/integration.rs
Related to https://github.com/CosmWasm/cosmwasm-examples/issues/94
Don't merge until cosmwasm/v0.11.0 is released
> escrow: Migrate to cosmwasm v0.11.0

- simple-option/Cargo.lock
- simple-option/Cargo.toml
- simple-option/src/contract.rs
- simple-option/src/error.rs
- simple-option/src/lib.rs
Related to https://github.com/CosmWasm/cosmwasm-examples/issues/94
Don't merge until cosmwasm/v0.11.0 is released
@webmaster128 New error API is very nice thanks!
> simple-option: Migrate to cosmwasm v0.11.0

- erc20/Cargo.lock
- erc20/Cargo.toml
- escrow/Cargo.lock
- escrow/Cargo.toml
- nameservice/Cargo.lock
- nameservice/Cargo.toml
- simple-option/Cargo.lock
- simple-option/Cargo.toml
- voting/Cargo.lock
- voting/Cargo.toml
> Update to 0.12.0

- erc20/Cargo.lock
- erc20/Cargo.toml
- escrow/Cargo.lock
- escrow/Cargo.toml
- nameservice/Cargo.lock
- nameservice/Cargo.toml
- simple-option/Cargo.lock
- simple-option/Cargo.toml
- voting/Cargo.lock
- voting/Cargo.toml
- voting/Developing.md
Related to https://github.com/CosmWasm/docs/issues/148
PR includes minor changes like rust version change in README files.
> Release 0.9.0

- README.md
Links broke after #118 was merged
> docs(README): fixed broken links to contracts
